USE master

---PROCEDEMOS A CREAR UN LOGIN PARA EL INICIO DE SESION

CREATE LOGIN PROEDUNP WITH PASSWORD ='123456'
GO

---PROCEDEMOS A USAR UNA BD PARA CREAR UN USUARIO

USE bdBodega

---CREACION DEL USUARIO

CREATE USER BODEGA FOR LOGIN PROEDUNP WITH DEFAULT_SCHEMA=dbo